
fastlane_version '2.131.0'

desc 'test lane'
lane :test do
  print "TEST SUCCESSFUL!"
end

platform :ios do

 desc 'Fetch certificates and provisioning profiles'
 lane :certificates do
 end

 desc 'Build the iOS application.'
 lane :build do
 end

 desc 'Ship to Testflight.'
 lane :beta do
 end

end

platform :android do

 desc 'Build the Android application.'
 lane :build do
 end

 desc 'Ship to Playstore Alpha track.'
 lane :alpha do
 end

end